<a href="https://colab.research.google.com/github/pshemach/PyTorch-Basics/blob/main/Linear_Regression_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import torch
import numpy as np

In [40]:
inputs = np.array([[70,40,60],[100,60,90],[90,50,130],[80,30,40],[60,70,100]], dtype='float32')
inputs

array([[ 70.,  40.,  60.],
       [100.,  60.,  90.],
       [ 90.,  50., 130.],
       [ 80.,  30.,  40.],
       [ 60.,  70., 100.]], dtype=float32)

In [41]:
targets = np.array([[58,77],[78,100],[122,130],[25,35],[113,120]], dtype='float32')
targets

array([[ 58.,  77.],
       [ 78., 100.],
       [122., 130.],
       [ 25.,  35.],
       [113., 120.]], dtype=float32)

In [42]:
inputs_tensor = torch.from_numpy(inputs)
targets_tensor = torch.from_numpy(targets)

print(inputs_tensor)
print(targets_tensor)

tensor([[ 70.,  40.,  60.],
        [100.,  60.,  90.],
        [ 90.,  50., 130.],
        [ 80.,  30.,  40.],
        [ 60.,  70., 100.]])
tensor([[ 58.,  77.],
        [ 78., 100.],
        [122., 130.],
        [ 25.,  35.],
        [113., 120.]])


In [43]:
weights = torch.randn(2, 3, requires_grad=True)
biases = torch.randn(2, requires_grad=True)

In [44]:
print('Weights\n',weights)
print('Biases\n',biases)

Weights
 tensor([[ 0.2229, -0.9241, -1.0751],
        [-1.7946,  0.3522, -1.0662]], requires_grad=True)
Biases
 tensor([ 0.1149, -1.3923], requires_grad=True)


In [45]:
inputs_tensor @ weights.t() + biases

tensor([[ -85.7545, -176.9037],
        [-129.8036, -255.6862],
        [-165.7969, -283.9117],
        [ -52.7821, -177.0470],
        [-158.7113, -191.0414]], grad_fn=<AddBackward0>)

In [46]:
def linear_regression_model(x, weights, biases):
  return x @ weights.t() + biases

In [47]:
harvest_prediction = linear_regression_model(inputs_tensor, weights=weights, biases=biases)
print(harvest_prediction)

tensor([[ -85.7545, -176.9037],
        [-129.8036, -255.6862],
        [-165.7969, -283.9117],
        [ -52.7821, -177.0470],
        [-158.7113, -191.0414]], grad_fn=<AddBackward0>)


In [48]:
print(targets_tensor)

tensor([[ 58.,  77.],
        [ 78., 100.],
        [122., 130.],
        [ 25.,  35.],
        [113., 120.]])


In [49]:
difference = harvest_prediction - targets_tensor
print(difference)

tensor([[-143.7545, -253.9037],
        [-207.8036, -355.6862],
        [-287.7969, -413.9117],
        [ -77.7822, -212.0470],
        [-271.7113, -311.0414]], grad_fn=<SubBackward0>)


In [50]:
difference*difference

tensor([[ 20665.3613,  64467.0820],
        [ 43182.3516, 126512.6875],
        [ 82827.0391, 171322.9062],
        [  6050.0630,  44963.9492],
        [ 73827.0312,  96746.7188]], grad_fn=<MulBackward0>)

In [51]:
torch.sum(difference*difference) / 10

tensor(73056.5156, grad_fn=<DivBackward0>)

In [52]:
torch.sum(difference*difference) / difference.numel()

tensor(73056.5156, grad_fn=<DivBackward0>)

In [53]:
def meanSquaredError(predictionTensor, targetsTensor):
  difference = predictionTensor - targetsTensor
  return torch.sum(difference*difference) / difference.numel()

In [54]:
model_loss = meanSquaredError(predictionTensor=harvest_prediction, targetsTensor=targets_tensor)
model_loss

tensor(73056.5156, grad_fn=<DivBackward0>)

In [55]:
model_loss.backward()

In [56]:
print('Metrix of the weights\n', weights)

Metrix of the weights
 tensor([[ 0.2229, -0.9241, -1.0751],
        [-1.7946,  0.3522, -1.0662]], requires_grad=True)


In [57]:
print('Derivative of the loss with regard to the weight elements')
print(weights.grad)

Derivative of the loss with regard to the weight elements
tensor([[-15854.0293, -10792.2998, -19004.7227],
        [-25244.0352, -16065.4424, -28128.1055]])


In [58]:
print(biases)
print(biases.grad)

tensor([ 0.1149, -1.3923], requires_grad=True)
tensor([-197.7697, -309.3180])


In [59]:
with torch.no_grad():
  weights -= weights.grad * 1e-5
  biases -= biases.grad * 1e-5

In [60]:
print(weights)

tensor([[ 0.3814, -0.8162, -0.8851],
        [-1.5422,  0.5128, -0.7850]], requires_grad=True)


In [61]:
print('Previous Prediction\n', harvest_prediction)
print('Previous Loss', model_loss)

new_pred = linear_regression_model(inputs_tensor, weights=weights, biases=biases)
new_loss = meanSquaredError(predictionTensor=new_pred, targetsTensor=targets_tensor)

print('New Prediction\n', new_pred)
print('New Loss\n', new_loss)

Previous Prediction
 tensor([[ -85.7545, -176.9037],
        [-129.8036, -255.6862],
        [-165.7969, -283.9117],
        [ -52.7821, -177.0470],
        [-158.7113, -191.0414]], grad_fn=<AddBackward0>)
Previous Loss tensor(73056.5156, grad_fn=<DivBackward0>)
New Prediction
 tensor([[ -58.9350, -135.9267],
        [ -90.3680, -195.4845],
        [-121.4240, -216.5897],
        [ -29.2574, -140.7779],
        [-122.6376, -136.5179]], grad_fn=<AddBackward0>)
New Loss
 tensor(50921.8398, grad_fn=<DivBackward0>)


In [62]:
weights.grad.zero_()
biases.grad.zero_()

tensor([0., 0.])

In [63]:
print(weights.grad)
print(biases.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [64]:
for i in range(2000):
  print("Epoch Number" + str(i))
  predictions = linear_regression_model(inputs_tensor, weights=weights, biases=biases)
  loss = meanSquaredError(predictionTensor=predictions, targetsTensor=targets_tensor)
  print('Loss'+ str(loss))
  loss.backward()
  with torch.no_grad():
    weights -= weights.grad * 1e-5
    biases -= biases.grad * 1e-5
    weights.grad.zero_()
    biases.grad.zero_()

Epoch Number0
Losstensor(50921.8398, grad_fn=<DivBackward0>)
Epoch Number1
Losstensor(35577.9805, grad_fn=<DivBackward0>)
Epoch Number2
Losstensor(24940.8086, grad_fn=<DivBackward0>)
Epoch Number3
Losstensor(17565.8086, grad_fn=<DivBackward0>)
Epoch Number4
Losstensor(12451.8154, grad_fn=<DivBackward0>)
Epoch Number5
Losstensor(8904.9277, grad_fn=<DivBackward0>)
Epoch Number6
Losstensor(6444.2075, grad_fn=<DivBackward0>)
Epoch Number7
Losstensor(4736.3213, grad_fn=<DivBackward0>)
Epoch Number8
Losstensor(3550.2402, grad_fn=<DivBackward0>)
Epoch Number9
Losstensor(2725.8384, grad_fn=<DivBackward0>)
Epoch Number10
Losstensor(2152.1348, grad_fn=<DivBackward0>)
Epoch Number11
Losstensor(1752.2090, grad_fn=<DivBackward0>)
Epoch Number12
Losstensor(1472.7483, grad_fn=<DivBackward0>)
Epoch Number13
Losstensor(1276.8016, grad_fn=<DivBackward0>)
Epoch Number14
Losstensor(1138.7590, grad_fn=<DivBackward0>)
Epoch Number15
Losstensor(1040.8691, grad_fn=<DivBackward0>)
Epoch Number16
Losstensor(970

In [65]:
print('Predictions\n', predictions)
print('Targets\n', targets_tensor)

Predictions
 tensor([[ 53.3453,  66.4061],
        [ 81.8432, 101.1297],
        [122.7640, 129.6382],
        [ 24.4748,  40.6305],
        [111.6613, 123.4151]], grad_fn=<AddBackward0>)
Targets
 tensor([[ 58.,  77.],
        [ 78., 100.],
        [122., 130.],
        [ 25.,  35.],
        [113., 120.]])


In [66]:
print('MSE:',meanSquaredError(predictionTensor=predictions, targetsTensor=targets_tensor))

MSE: tensor(19.6092, grad_fn=<DivBackward0>)
