<a href="https://colab.research.google.com/github/pshemach/PyTorch-Basics/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor1 = torch.tensor(8)
tensor1

tensor(8)

In [ ]:
tensor1.dtype

torch.int64

In [ ]:
tensor2 = torch.tensor([10,20,30,40])
print(tensor2)
print(tensor2.dtype)

tensor([10, 20, 30, 40])
torch.int64


In [ ]:
tensor2 = torch.tensor([10,20.0,30,40])
print(tensor2)
print(tensor2.dtype)

tensor([10., 20., 30., 40.])
torch.float32


In [ ]:
tensor2d = torch.tensor([[12.0,2],[45,2],[3,2],[0,87]])
print(tensor2d)
print(tensor2d.dtype)

tensor([[12.,  2.],
        [45.,  2.],
        [ 3.,  2.],
        [ 0., 87.]])
torch.float32


In [ ]:
tensor3d = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[10,20,30],[40,50,60]]
])

print(tensor3d)
print(tensor3d.dtype)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]])
torch.int64


In [ ]:
stream_list = ['netflix','hulu','prime video','hbo max']

from sklearn import preprocessing
stringEncoder = preprocessing.LabelEncoder()
targets = stringEncoder.fit_transform(stream_list)
tensorList = torch.as_tensor(targets)
print(tensorList)
print(tensorList.dtype)

tensor([2, 1, 3, 0])
torch.int64


In [ ]:
print(tensor1)
print(f'Shape {tensor1.shape}\n')
print(tensor2)
print(f'Shape {tensor2.shape}\n')
print(tensor2d)
print(f'Shape {tensor2d.shape}\n')
print(tensor3d)
print(f'Shape {tensor3d.shape}\n')
print(tensorList)
print(f'Shape {tensorList.shape}\n')

tensor(8)
Shape torch.Size([])

tensor([10., 20., 30., 40.])
Shape torch.Size([4])

tensor([[12.,  2.],
        [45.,  2.],
        [ 3.,  2.],
        [ 0., 87.]])
Shape torch.Size([4, 2])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]])
Shape torch.Size([2, 2, 3])

tensor([2, 1, 3, 0])
Shape torch.Size([4])



In [ ]:
#y = mx + c

x = torch.tensor(5.)
m = torch.tensor(10., requires_grad=True)
c = torch.tensor(20., requires_grad=True)

In [ ]:
y = m*x + c
y

tensor(70., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
print("dy/dx", x.grad)
print("dy/dm", m.grad)
print("dy/dc", c.grad)

dy/dx None
dy/dm tensor(5.)
dy/dc tensor(1.)


In [ ]:
tensor1 = torch.full((3,2), 20)

In [ ]:
tensor1

tensor([[20, 20],
        [20, 20],
        [20, 20]])

In [ ]:
tensor2 = torch.tensor([[20,32],[72,85],[78,30]])
print(tensor2)

tensor([[20, 32],
        [72, 85],
        [78, 30]])


In [ ]:
#concatination

tensorConcat = torch.cat((tensor1,tensor2))

In [ ]:
print(tensorConcat)

tensor([[20, 20],
        [20, 20],
        [20, 20],
        [20, 32],
        [72, 85],
        [78, 30]])


In [ ]:
tensorSin = torch.sin(tensorConcat)
tensorSin

tensor([[ 0.9129,  0.9129],
        [ 0.9129,  0.9129],
        [ 0.9129,  0.9129],
        [ 0.9129,  0.5514],
        [ 0.2538, -0.1761],
        [ 0.5140, -0.9880]])

In [ ]:
reshapedTensor = tensorSin.reshape(3,2,2)
reshapedTensor

tensor([[[ 0.9129,  0.9129],
         [ 0.9129,  0.9129]],

        [[ 0.9129,  0.9129],
         [ 0.9129,  0.5514]],

        [[ 0.2538, -0.1761],
         [ 0.5140, -0.9880]]])

In [ ]:
import numpy as np

numpyArray = np.array([[10.,20.],[30.,40.]])
numpyArray

array([[10., 20.],
       [30., 40.]])

In [ ]:
torchArray = torch.from_numpy(numpyArray)
torchArray

tensor([[10., 20.],
        [30., 40.]], dtype=torch.float64)

In [ ]:
print(numpyArray.dtype)
print(torchArray.dtype)

float64
torch.float64


In [ ]:
numpyArray = torchArray.numpy()
numpyArray

array([[10., 20.],
       [30., 40.]])